Sincofipy --> biblioteca python com dados do Sistema de Informações Contábeis e Fiscais do Setor Público Brasileiro

    get_fiscal(): Coleta dados do Relatório de Gestão Fiscal --> RGF - Relatório de Gestão Fiscal
    get_budget(): Coleta dados do Resumo da Execução Orçamentária ---> RREO ---> Relatório Resumido da Exceução Orçamentária
    get_annual_acc(): Busca informações de contas anuais
    get_info(): Retorna dados cadastrais básicos de entes federativos.

Problemas com Pip install...

---> Solução no terminal do Vs code
-----> python -m pip install openpyxl p/ termos exteriores ao python

# Importando

In [17]:
import siconfipy
import pandas as pd
import openpyxl

Extraindo relatório Resumido de Execução Orçamentária

Existe diversos parâmetros no Siconfipy -> Escolhemos treinar orçamento
Dentro da função temos diversos argumentos

---> ano

---> periodo = bimestral --> advenhem de dados do RREO

---> código = entes estaduais definidos pelo IBGE


criamos um dataframe comum e simples

--> df_orçamento --> colocamos a função e chamamos ele

In [18]:
from siconfipy import get_budget
df_orçamento = get_budget(year = 2025, period = [1, 2, 3, 4, 5, 6], cod = 27)
df_orçamento

,exercicio,demonstrativo,periodo,periodicidade,instituicao,cod_ibge,uf,populacao,anexo,esfera,rotulo,coluna,cod_conta,conta,valor
0,2025,RREO,1,B,Governo do Estado de Alagoas,27,AL,3125254,RREO-Anexo 01,E,Padrão,PREVISÃO INICIAL,ReceitasExcetoIntraOrcamentarias,RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I),1.777132e+10
1,2025,RREO,1,B,Governo do Estado de Alagoas,27,AL,3125254,RREO-Anexo 01,E,Padrão,PREVISÃO ATUALIZADA (a),ReceitasExcetoIntraOrcamentarias,RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I),1.777132e+10
2,2025,RREO,1,B,Governo do Estado de Alagoas,27,AL,3125254,RREO-Anexo 01,E,Padrão,No Bimestre (b),ReceitasExcetoIntraOrcamentarias,RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I),3.730202e+09
3,2025,RREO,1,B,Governo do Estado de Alagoas,27,AL,3125254,RREO-Anexo 01,E,Padrão,% (b/a),ReceitasExcetoIntraOrcamentarias,RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I),2.099000e+01
4,2025,RREO,1,B,Governo do Estado de Alagoas,27,AL,3125254,RREO-Anexo 01,E,Padrão,Até o Bimestre (c),ReceitasExcetoIntraOrcamentarias,RECEITAS (EXCETO INTRA-ORÇAMENTÁRIAS) (I),3.730202e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4320,2025,RREO,6,B,Governo do Estado de Alagoas,27,AL,3125254,RREO-Anexo 14,E,Padrão,Valor Apurado no Exercício,AplicacaoDosRecursosDaAlienacaoDeAtivosDemonst...,Aplicação dos Recursos da Alienação de Ativos,1.249565e+07
4321,2025,RREO,6,B,Governo do Estado de Alagoas,27,AL,3125254,RREO-Anexo 14,E,Padrão,Saldo a Realizar,AplicacaoDosRecursosDaAlienacaoDeAtivosDemonst...,Aplicação dos Recursos da Alienação de Ativos,1.454138e+07
4322,2025,RREO,6,B,Governo do Estado de Alagoas,27,AL,3125254,RREO-Anexo 14,E,Padrão,Valor Apurado Até o Bimestre,AplicacaoTotalDasDespesasComAcoesEServicosPubl...,Despesas com Ações e Serviços Públicos de Saúd...,2.336964e+09
4323,2025,RREO,6,B,Governo do Estado de Alagoas,27,AL,3125254,RREO-Anexo 14,E,Padrão,% Mínimo a Aplicar no Exercício,AplicacaoTotalDasDespesasComAcoesEServicosPubl...,Despesas com Ações e Serviços Públicos de Saúd...,1.200000e+01
4324,2025,RREO,6,B,Governo do Estado de Alagoas,27,AL,3125254,RREO-Anexo 14,E,Padrão,% Aplicado Até o Bimestre,AplicacaoTotalDasDespesasComAcoesEServicosPubl...,Despesas com Ações e Serviços Públicos de Saúd...,1.338000e+01

CTRL + S --> SALVAR

--> .to_excel("nome", índice=)

Obs.:
- O caminho que o arquivo é direcionado é a pasta onde o notebook se encontra
- Para abrir no explorer do Vs Code
---> ctrl + K ou O


---->>> ctrl+; 
--------> tudo vira comentários

In [19]:
# df_orc_excel = df_orçamento.to_excel("orçament_alagoas_bimestr_RREO_2025.xlsx", index = False)
# df_orc_excel

Selecionado apenas as colunas necessárias

In [20]:
df_select = df_orçamento[['uf','exercicio','periodo', 'periodicidade','coluna','valor']]
df_select

,uf,exercicio,periodo,periodicidade,coluna,valor
0,AL,2025,1,B,PREVISÃO INICIAL,1.777132e+10
1,AL,2025,1,B,PREVISÃO ATUALIZADA (a),1.777132e+10
2,AL,2025,1,B,No Bimestre (b),3.730202e+09
3,AL,2025,1,B,% (b/a),2.099000e+01
4,AL,2025,1,B,Até o Bimestre (c),3.730202e+09
...,...,...,...,...,...,...
4320,AL,2025,6,B,Valor Apurado no Exercício,1.249565e+07
4321,AL,2025,6,B,Saldo a Realizar,1.454138e+07
4322,AL,2025,6,B,Valor Apurado Até o Bimestre,2.336964e+09
4323,AL,2025,6,B,% Mínimo a Aplicar no Exercício,1.200000e+01
4324,AL,2025,6,B,% Aplicado Até o Bimestre,1.338000e+01

Alterando o texto de dentro de uma coluna
&
Somando as colunas

---> [coluna]..astype(str).str.replace('nome original' , 'Novo nome') ##Renomeando

----> df['coluna].astype(str) + " - " + renomeando

astype(devem ser idênticos)


---> Assim conseguimos modificar o "valor" dentro das células das colunas

Obs.
ctrl + shift + L --> selec. todas as palavras

In [21]:
df_select['periodicidade'] = (
    df_select['periodo'].astype(str) 
    + " - " 
    + df_select['periodicidade'].astype(str).str.replace('B', 'bimestre')
)

df_select

,uf,exercicio,periodo,periodicidade,coluna,valor
0,AL,2025,1,1 - bimestre,PREVISÃO INICIAL,1.777132e+10
1,AL,2025,1,1 - bimestre,PREVISÃO ATUALIZADA (a),1.777132e+10
2,AL,2025,1,1 - bimestre,No Bimestre (b),3.730202e+09
3,AL,2025,1,1 - bimestre,% (b/a),2.099000e+01
4,AL,2025,1,1 - bimestre,Até o Bimestre (c),3.730202e+09
...,...,...,...,...,...,...
4320,AL,2025,6,6 - bimestre,Valor Apurado no Exercício,1.249565e+07
4321,AL,2025,6,6 - bimestre,Saldo a Realizar,1.454138e+07
4322,AL,2025,6,6 - bimestre,Valor Apurado Até o Bimestre,2.336964e+09
4323,AL,2025,6,6 - bimestre,% Mínimo a Aplicar no Exercício,1.200000e+01
4324,AL,2025,6,6 - bimestre,% Aplicado Até o Bimestre,1.338000e+01

Renomeando
df.rename(colunas = {chaves com 'nome original' : 'Novo nome'})


obs. Para salvar na memória é necessário ou modificar o df original ou criar um novo df

In [22]:
df_select_1 = df_select.rename(columns ={'uf':'Estado', 'exercicio':'Ano', 'periodicidade':'Bimestre', 'coluna':'Descrição', 'valor': 'Valor (R$)'})
df_select_1

,Estado,Ano,periodo,Bimestre,Descrição,Valor (R$)
0,AL,2025,1,1 - bimestre,PREVISÃO INICIAL,1.777132e+10
1,AL,2025,1,1 - bimestre,PREVISÃO ATUALIZADA (a),1.777132e+10
2,AL,2025,1,1 - bimestre,No Bimestre (b),3.730202e+09
3,AL,2025,1,1 - bimestre,% (b/a),2.099000e+01
4,AL,2025,1,1 - bimestre,Até o Bimestre (c),3.730202e+09
...,...,...,...,...,...,...
4320,AL,2025,6,6 - bimestre,Valor Apurado no Exercício,1.249565e+07
4321,AL,2025,6,6 - bimestre,Saldo a Realizar,1.454138e+07
4322,AL,2025,6,6 - bimestre,Valor Apurado Até o Bimestre,2.336964e+09
4323,AL,2025,6,6 - bimestre,% Mínimo a Aplicar no Exercício,1.200000e+01
4324,AL,2025,6,6 - bimestre,% Aplicado Até o Bimestre,1.338000e+01

In [23]:
df_oficial = df_select_1[['Estado', 'Ano', 'Bimestre','Descrição', 'Valor (R$)']]
df_oficial

     Estado   Ano      Bimestre                        Descrição    Valor (R$)
0        AL  2025  1 - bimestre                 PREVISÃO INICIAL  1.777132e+10
1        AL  2025  1 - bimestre          PREVISÃO ATUALIZADA (a)  1.777132e+10
2        AL  2025  1 - bimestre                  No Bimestre (b)  3.730202e+09
3        AL  2025  1 - bimestre                          % (b/a)  2.099000e+01
4        AL  2025  1 - bimestre               Até o Bimestre (c)  3.730202e+09
...     ...   ...           ...                              ...           ...
4320     AL  2025  6 - bimestre       Valor Apurado no Exercício  1.249565e+07
4321     AL  2025  6 - bimestre                 Saldo a Realizar  1.454138e+07
4322     AL  2025  6 - bimestre     Valor Apurado Até o Bimestre  2.336964e+09
4323     AL  2025  6 - bimestre  % Mínimo a Aplicar no Exercício  1.200000e+01
4324     AL  2025  6 - bimestre        % Aplicado Até o Bimestre  1.338000e+01

[20002 rows x 5 columns]

Baixando Planilha de dados sobre o orçamento de 2025 de Alagoas

In [24]:
# df_oficial.to_excel("RREO_filtrado_AL_2025.xlsx", index = False)

Filtrando informações específicas por dataframe

---> Basicamente é aplicação de filtros


----> .isin([...] é para selecionar vários textos

---> aqui tem prestar atenção entre (), [] e {}
- () - serve para funções (sempre tendo protagonismo para os argumentos) e listas/tuplas
- [] - serve para pegar itens específicos da indexação, ex: posição 0 == [0]; condicionados ao acesso, usado principalmente em filtros e colunas
- {} - Serve para guardar informações, ex: {'nome': 'Ana', 'idade': 30} // chave: valor; tem grande serventia em f-strings --> ex: f"O resultado é {df_filtrado}"

In [25]:
df_filtrado = df_oficial[df_oficial['Descrição'].isin(['DESPESAS EMPENHADAS',
    'DESPESAS EMPENHADAS NO BIMESTRE',
    'LIQUIDADOS',
    'Saldo a Pagar',
    'SALDO ATUAL',
    'Saldo a Realizar'
])]

df_filtrado

     Estado   Ano      Bimestre                        Descrição    Valor (R$)
264      AL  2025  1 - bimestre  DESPESAS EMPENHADAS NO BIMESTRE  3.875835e+09
273      AL  2025  1 - bimestre  DESPESAS EMPENHADAS NO BIMESTRE  3.369236e+09
282      AL  2025  1 - bimestre  DESPESAS EMPENHADAS NO BIMESTRE  2.164205e+09
291      AL  2025  1 - bimestre  DESPESAS EMPENHADAS NO BIMESTRE  2.970875e+08
300      AL  2025  1 - bimestre  DESPESAS EMPENHADAS NO BIMESTRE  9.079436e+08
...     ...   ...           ...                              ...           ...
4262     AL  2025  6 - bimestre                    Saldo a Pagar  1.619737e+06
4266     AL  2025  6 - bimestre                    Saldo a Pagar  1.142500e+04
4270     AL  2025  6 - bimestre                    Saldo a Pagar  1.995044e+08
4319     AL  2025  6 - bimestre                 Saldo a Realizar -1.986059e+07
4321     AL  2025  6 - bimestre                 Saldo a Realizar  1.454138e+07

[1283 rows x 5 columns]

Zerando índice do df

Existem duas formas gerais que dependem examente de 
--> .reset_index()

1. com novo df
-->  df_ciclano = df_blabla.reset_index(drop=true)
---> df_ciclano



2. no mesmo df
--> df_fulano.reset_index(drop = True)


obs. True e False sempre devem ser maiúsuclo para funcionar

In [28]:
df_filtrado.reset_index(drop=True, inplace=True)
df_filtrado

     Estado   Ano      Bimestre                        Descrição    Valor (R$)
0        AL  2025  1 - bimestre  DESPESAS EMPENHADAS NO BIMESTRE  3.875835e+09
1        AL  2025  1 - bimestre  DESPESAS EMPENHADAS NO BIMESTRE  3.369236e+09
2        AL  2025  1 - bimestre  DESPESAS EMPENHADAS NO BIMESTRE  2.164205e+09
3        AL  2025  1 - bimestre  DESPESAS EMPENHADAS NO BIMESTRE  2.970875e+08
4        AL  2025  1 - bimestre  DESPESAS EMPENHADAS NO BIMESTRE  9.079436e+08
...     ...   ...           ...                              ...           ...
1278     AL  2025  6 - bimestre                    Saldo a Pagar  1.619737e+06
1279     AL  2025  6 - bimestre                    Saldo a Pagar  1.142500e+04
1280     AL  2025  6 - bimestre                    Saldo a Pagar  1.995044e+08
1281     AL  2025  6 - bimestre                 Saldo a Realizar -1.986059e+07
1282     AL  2025  6 - bimestre                 Saldo a Realizar  1.454138e+07

[1283 rows x 5 columns]

In [ ]:
# df_filtrado.to_excel("Siconfipy_filtr_2025_orçamento_AL", index = False)

In [ ]:
# Conta no Git
# Caminho para Git push e pull

# Push --> Suas alterações --> "empurrar"

# Pull --> Alterações de terceiros --> "puxar"

# 1. baixar o git bash


# 2. No git hub
# - Criar repositório
# - Deixar público de início e depois habilitar "Add a README file" (Leia-me em tradução livre)

# - Relação entre o Git Hub e o Git Bash
# Hub: no novo repositório -> code -> copiar link
# ----> PC: Na pasta do projeto 
# ----> Bash: git clone e copiar com "paste"
# -------> Abri todo esse processo no VS code --> na pasta abra o git bash --> "code ."

# obs. tudo apenas funciona quando o projeto está salvo e nada da pasta atual está aberto (Excel e afins)

# Processos dentro do terminal com o power bash
# plote:

# ----> git config --global user.email "seu email@@"

# ---> git config --global user.name "seu usuário do git"

# - git init --> Pasta atual em repositório
# - git branch -M main --> obrigatório --> 
# - git add . --> preparando para envio
# - git commit -m "Version 1.0"
# - git remote add origin "URL do meu repositório"
# - git pull -> puxando como formato de confirmação
# - git push -u origin main --> Enviando as novas informações

# Depois basta compartilhar apenas a URL do projeto.